version: 2
jobs:
  build-gimp-2-10:
    macos:
        xcode: "12.2.0"

    steps:
        - checkout
        - run:
            name: Cleanup /usr/local
            command: sudo rm -rf /usr/local/*
        - run:
            name: Setup rust
            command: curl https://sh.rustup.rs -sSf | sh -s -- -y
        - run:
            name: Setup Python3
            command: |
              cd ~/
              curl -L 'https://www.python.org/ftp/python/3.6.8/python-3.6.8-macosx10.9.pkg' > python-3.6.8-macosx10.9.pkg
              sudo installer -pkg python-3.6.8-macosx10.9.pkg -target /
        - run:
            name: Setup 10.12 SDK
            command: |
              cd /Library/Developer/CommandLineTools/SDKs
              sudo curl -L 'https://github.com/phracker/MacOSX-SDKs/releases/download/11.0-11.1/MacOSX11.1.sdk.tar.xz' | sudo tar -xzf -
              echo 'export SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk' > ~/.profile
              echo 'export MACOSX_DEPLOYMENT_TARGET=11.1' >> ~/.profile
        - restore_cache:
            keys:
              - jhbuild-v12
        - run:
            name: Setup JHBuild
            command: |
              cd $HOME
              mkdir -p ~/.config && mv ~/project/jhbuildrc-gtk-osx-gimp ~/.config/jhbuildrc-custom
              curl https://gitlab.gnome.org/yoyonamite/gtk-osx/-/raw/arm64-cross/gtk-osx-setup.sh > gtk-osx-setup.sh
              chmod +x gtk-osx-setup.sh
              echo 'export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH:$HOME/.new_local/bin"' >> ~/.profile
              echo 'export ARCHFLAGS="-arch arm64"' >> ~/.profile
              source ~/.profile
              PIPENV_YES=1 ./gtk-osx-setup.sh
              $HOME/.new_local/bin/jhbuild bootstrap-gtk-osx-gimp
              cat ~/.profile
        - save_cache:
            paths:
              - ~/.new_local
              - ~/gtk
              - ~/.config
            key: jhbuild-v12
        - run:
            name:  Save binaries
            command: tar -cvzf files.tar.gz ~/
        - store_artifacts:
            path: /tmp/artifacts
            destination: builds

workflows:
  version: 2
  build-different-versions:
    jobs:
      - build-gimp-2-10
